### ISSUE TITLE
required package does not exist

### ISSUE THREAD

**Issue by pebbe** [Depado/bfchroma#10] opened 2020-04-22 17:22 UTC
this package listed in go.mod does not exist: github.com/russross/blackfriday/v2

**Comment by Depado** [comment] 2020-05-04 16:21
Strange, it does exist :thinking:

**Comment by TACIXAT** [comment] 2020-05-18 08:09
They've switched to `gopkg.in/russross/blackfriday.v2`. I can't go get `github.com/russross/blackfriday/v2`. This repo seems to use that so I get the failure too. It is odd though because play.golang.org works fine with the old url.

**Comment by Depado** [comment] 2020-05-19 07:33
It seems that issue is being discussed over here https://github.com/russross/blackfriday/issues/587
I don't get why it suddenly broke. 
Just out of curiosity, how are you trying to `go get` the v2 version ?

**Comment by Depado** [comment] 2020-05-19 07:39
So after a quick test, I can't reproduce.

`go.mod`
```
module github.com/Depado/bfchromatest

go 1.14

require (
	github.com/Depado/bfchroma v1.2.0
	github.com/alecthomas/chroma v0.7.3 // indirect
	github.com/russross/blackfriday/v2 v2.0.1
)
```

`main.go`
```go
package main

import (
	"fmt"

	"github.com/Depado/bfchroma"

	bf "github.com/russross/blackfriday/v2"
)

func main() {
	md := []byte("# hello world")
	html := bf.Run([]byte(md), bf.WithRenderer(bfchroma.NewRenderer()))

	fmt.Println(string(html))
}
```

```sh
$ go run main.go
<h1>hello world</h1>
```

Even after I `go get -u`, it doesn't fail. 
Are you both using go modules ?

**Comment by pebbe** [comment] 2020-05-21 15:49
Start with an empty `~/go`:

```
$ go get -v github.com/Depado/bfchroma
github.com/Depado/bfchroma (download)
created GOPATH=/home/peter/go; see 'go help gopath'
github.com/alecthomas/chroma (download)
github.com/dlclark/regexp2 (download)
github.com/danwakefield/fnmatch (download)
github.com/russross/blackfriday (download)
package github.com/russross/blackfriday/v2: cannot find package "github.com/russross/blackfriday/v2" in any of:
        /my/opt/go/src/github.com/russross/blackfriday/v2 (from $GOROOT)
        /home/peter/go/src/github.com/russross/blackfriday/v2 (from $GOPATH)
```

```
go version go1.14.3 linux/amd64
```

**Comment by Depado** [comment] 2020-06-29 08:33
Alright, I'm completely lost, if anyone has the knowledge to help me out with this one.
I'm starting fresh with a new `GOPATH` every time using `mktemp`.

### Outside of a go module project

```sh
env GOPATH=(mktemp -d -t gopath-XXXXXXXXXX) go get -v github.com/Depado/bfchroma
github.com/Depado/bfchroma (download)
github.com/alecthomas/chroma (download)
github.com/dlclark/regexp2 (download)
github.com/danwakefield/fnmatch (download)
github.com/russross/blackfriday (download)
package github.com/russross/blackfriday/v2: cannot find package "github.com/russross/blackfriday/v2" in any of:
	/home/paul/go/src/github.com/russross/blackfriday/v2 (from $GOROOT)
	/tmp/gopath-WHL5VOgK5F/src/github.com/russross/blackfriday/v2 (from $GOPATH)
```

### Inside a go module project

I'll reuse the one described in my latest comment:

```go
// file: go.mod
module github.com/Depado/bfchromatest

go 1.14

require (
	github.com/Depado/bfchroma v1.2.0
	github.com/alecthomas/chroma v0.7.3 // indirect
	github.com/russross/blackfriday/v2 v2.0.1
)
```

```
env GOPATH=(mktemp -d -t gopath-XXXXXXXXXX) go get -v github.com/Depado/bfchroma
go: downloading github.com/Depado/bfchroma v1.2.0
go: downloading github.com/alecthomas/chroma v0.7.3
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading github.com/dlclark/regexp2 v1.2.0
go: downloading github.com/danwakefield/fnmatch v0.0.0-20160403171240-cbb64ac3d964
github.com/danwakefield/fnmatch
github.com/shurcooL/sanitized_anchor_name
github.com/dlclark/regexp2/syntax
github.com/russross/blackfriday/v2
github.com/dlclark/regexp2
github.com/alecthomas/chroma
github.com/alecthomas/chroma/lexers/internal
github.com/alecthomas/chroma/formatters/html
github.com/alecthomas/chroma/styles
github.com/alecthomas/chroma/lexers/b
github.com/alecthomas/chroma/lexers/a
github.com/alecthomas/chroma/lexers/p
github.com/alecthomas/chroma/lexers/e
github.com/alecthomas/chroma/lexers/j
github.com/alecthomas/chroma/lexers/f
github.com/alecthomas/chroma/lexers/i
github.com/alecthomas/chroma/lexers/k
github.com/alecthomas/chroma/lexers/l
github.com/alecthomas/chroma/lexers/n
github.com/alecthomas/chroma/lexers/o
github.com/alecthomas/chroma/lexers/q
github.com/alecthomas/chroma/lexers/r
github.com/alecthomas/chroma/lexers/d
github.com/alecthomas/chroma/lexers/t
github.com/alecthomas/chroma/lexers/w
github.com/alecthomas/chroma/lexers/x
github.com/alecthomas/chroma/lexers/y
github.com/alecthomas/chroma/lexers/v
github.com/alecthomas/chroma/lexers/c
github.com/alecthomas/chroma/lexers/h
github.com/alecthomas/chroma/lexers/circular
github.com/alecthomas/chroma/lexers/g
github.com/alecthomas/chroma/lexers/m
github.com/alecthomas/chroma/lexers/s
github.com/alecthomas/chroma/lexers
github.com/Depado/bfchroma
```

I can't seem to figure out the difference between `go get`ing a package inside a project and `go get`ing a package outside of a project. I tried ensuring this is the latest version of the repo using `@master` when go getting but that doesn't change anything since `master` points to the `v1.2.0` release anyway.

**Comment by Depado** [comment] 2020-09-21 13:33
So I've been digging around lately.
Turns out, I'm using spf13/cobra, which in turn uses a lab called `md2man` that depends on `github.com/russross/blackfriday/v2` so I can't rollback to using the `gopkg.in` version. But I don't understand how it can't be build:

```
$ git clone git@github.com:Depado/smallblog.git
Clonage dans 'smallblog'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 698 (delta 4), reused 12 (delta 4), pack-reused 685
Réception d'objets: 100% (698/698), 1.41 Mio | 3.25 Mio/s, fait.
Résolution des deltas: 100% (415/415), fait.

$ cd smallblog/

$ env GOPATH=(mktemp -d -t gopath-XXXXXXXXXX) go build
go: downloading github.com/spf13/cobra v1.0.0
go: downloading github.com/sirupsen/logrus v1.6.0
go: downloading github.com/spf13/viper v1.7.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/Depado/bfplus v0.2.0
go: downloading github.com/gin-gonic/gin v1.6.3
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading github.com/stvp/slug v0.0.0-20150928221549-5ab8191bb1fe
go: downloading github.com/gorilla/feeds v1.1.1
go: downloading github.com/onrik/logrus v0.6.0
go: downloading github.com/otiai10/copy v1.2.0
go: downloading golang.org/x/sys v0.0.0-20200625212154-ddb9806d33ae
go: downloading github.com/mitchellh/mapstructure v1.3.2
go: downloading github.com/alecthomas/chroma v0.7.3
go: downloading github.com/magiconair/properties v1.8.1
go: downloading github.com/subosito/gotenv v1.2.0
go: downloading gopkg.in/ini.v1 v1.57.0
go: downloading golang.org/x/text v0.3.3
go: downloading github.com/pelletier/go-toml v1.8.0
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/spf13/cast v1.3.1
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/golang/protobuf v1.4.2
go: downloading github.com/spf13/afero v1.3.0
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading google.golang.org/protobuf v1.25.0
go: downloading github.com/gin-contrib/sse v0.1.0
go: downloading github.com/ugorji/go v1.1.7
go: downloading github.com/ugorji/go/codec v1.1.7
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/go-playground/validator/v10 v10.3.0
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/danwakefield/fnmatch v0.0.0-20160403171240-cbb64ac3d964
go: downloading github.com/dlclark/regexp2 v1.2.0
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading github.com/leodido/go-urn v1.2.0
go: downloading github.com/go-playground/universal-translator v0.17.0
go: downloading github.com/go-playground/locales v0.13.0
```

So I'm going to close this, because I just can't figure out what's going on.

**Closed by Depado** 2020-09-21 13:33 UTC
